// flow-typed signature: 48c03fc60f2b59a84866040051392720
// flow-typed version: <<STUB>>/async-redis_v^1.1.5/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-redis/examples/create-redis' {
  declare module.exports: any;
}

declare module 'async-redis/src/index' {
  declare module.exports: any;
}

declare module 'async-redis/src/object-decorator' {
  declare module.exports: any;
}

declare module 'async-redis/test/integration/commands/common.spec' {
  declare module.exports: any;
}

declare module 'async-redis/test/integration/create-client.spec' {
  declare module.exports: any;
}

declare module 'async-redis/test/integration/decorate-redis.spec' {
  declare module.exports: any;
}

declare module 'async-redis/test/setup' {
  declare module.exports: any;
}

declare module 'async-redis/test/unit/object-decorator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-redis/examples/create-redis.js' {
  declare module.exports: $Exports<'async-redis/examples/create-redis'>;
}
declare module 'async-redis/src/index.js' {
  declare module.exports: $Exports<'async-redis/src/index'>;
}
declare module 'async-redis/src/object-decorator.js' {
  declare module.exports: $Exports<'async-redis/src/object-decorator'>;
}
declare module 'async-redis/test/integration/commands/common.spec.js' {
  declare module.exports: $Exports<'async-redis/test/integration/commands/common.spec'>;
}
declare module 'async-redis/test/integration/create-client.spec.js' {
  declare module.exports: $Exports<'async-redis/test/integration/create-client.spec'>;
}
declare module 'async-redis/test/integration/decorate-redis.spec.js' {
  declare module.exports: $Exports<'async-redis/test/integration/decorate-redis.spec'>;
}
declare module 'async-redis/test/setup.js' {
  declare module.exports: $Exports<'async-redis/test/setup'>;
}
declare module 'async-redis/test/unit/object-decorator.js' {
  declare module.exports: $Exports<'async-redis/test/unit/object-decorator'>;
}
