// flow-typed signature: 12f73ae750155c20670a206d7ae22b89
// flow-typed version: <<STUB>>/glslify_v^7.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glslify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glslify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glslify/bin' {
  declare module.exports: any;
}

declare module 'glslify/browser' {
  declare module.exports: any;
}

declare module 'glslify/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glslify/bin.js' {
  declare module.exports: $Exports<'glslify/bin'>;
}
declare module 'glslify/browser.js' {
  declare module.exports: $Exports<'glslify/browser'>;
}
declare module 'glslify/index' {
  declare module.exports: $Exports<'glslify'>;
}
declare module 'glslify/index.js' {
  declare module.exports: $Exports<'glslify'>;
}
declare module 'glslify/transform.js' {
  declare module.exports: $Exports<'glslify/transform'>;
}
