// flow-typed signature: a1e4c9a20ddcdef870e68b292bd71347
// flow-typed version: <<STUB>>/glsl-noise_v^0.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glsl-noise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glsl-noise' {
  declare module.exports: any;
}
