// flow-typed signature: 2fe7b5f89ab4acf8a5b1d9178bbf8acc
// flow-typed version: <<STUB>>/react-dnd-touch-backend-cjs_v^9.5.1/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-touch-backend-cjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-touch-backend-cjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-touch-backend-cjs/lib' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/OptionsReader' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/TouchBackend' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/utils/math' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/utils/offsets' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/utils/predicates' {
  declare module.exports: any;
}

declare module 'react-dnd-touch-backend-cjs/lib/utils/supportsPassive' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-touch-backend-cjs/lib/index' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/interfaces.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/interfaces'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/OptionsReader.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/OptionsReader'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/TouchBackend.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/TouchBackend'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/utils/math.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/utils/math'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/utils/offsets.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/utils/offsets'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/utils/predicates.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/utils/predicates'>;
}
declare module 'react-dnd-touch-backend-cjs/lib/utils/supportsPassive.js' {
  declare module.exports: $Exports<'react-dnd-touch-backend-cjs/lib/utils/supportsPassive'>;
}
