// flow-typed signature: 60c1c55efc414449b3260a204f6c5d71
// flow-typed version: <<STUB>>/react-dnd-multi-backend_v^4.0.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-multi-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-multi-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-multi-backend/lib/HTML5toTouch' {
  declare module.exports: any;
}

declare module 'react-dnd-multi-backend/lib' {
  declare module.exports: any;
}

declare module 'react-dnd-multi-backend/lib/Preview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-multi-backend/lib/HTML5toTouch.js' {
  declare module.exports: $Exports<'react-dnd-multi-backend/lib/HTML5toTouch'>;
}
declare module 'react-dnd-multi-backend/lib/index' {
  declare module.exports: $Exports<'react-dnd-multi-backend/lib'>;
}
declare module 'react-dnd-multi-backend/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-multi-backend/lib'>;
}
declare module 'react-dnd-multi-backend/lib/Preview.js' {
  declare module.exports: $Exports<'react-dnd-multi-backend/lib/Preview'>;
}
