// flow-typed signature: 7fca1ddfb34c3b059d913ab694f69949
// flow-typed version: <<STUB>>/touches_v^1.2.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'touches'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'touches' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'touches/index' {
  declare module.exports: $Exports<'touches'>;
}
declare module 'touches/index.js' {
  declare module.exports: $Exports<'touches'>;
}
